[theme]
primaryColor = "#059669"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
base = "light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
